<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

/**
 * Fix icons in custom header template for icons that were renamed in 7.6
 *
 * Since all icons were renamed in 7.6, usually with fa- prefix instead of icon-,
 * all prefixes should be updated. There are some icons that were renamed entirely.
 *
 * @see UIUX-1687 for related issues
 */
class SugarUpgradeFixIconNameChanges extends UpgradeScript
{
    public $order = 7420;
    public $type = self::UPGRADE_CUSTOM;

    public $iconPattern = '/icon-(plus|reorder|upload)/';
    public $foundPattern = false;
    /**
     * Icon replacements to change
     *
     * @var array
     */
    public $upgradeIcons = array(
        'icon-plus' => 'fa-plus',
        'icon-reorder' => 'fa-bars',
        'icon-upload' => 'fa-upload',
    );

    public function run()
    {
        if (!version_compare($this->from_version, '7.0', '>') || !version_compare($this->from_version, '7.6', '<')) {
            // only need to run this upgrading for greater than 7.0 and less than 7.7
            return;
        }
        $customModules = $this->getCustomModules();

        if (empty($customModules)) {
            // No MB modules - nothing to do
            return;
        }

        foreach($customModules as $module) {
            $path = 'modules/' . $module . '/clients/base/menus/header/header.php';
            $this->foundPattern = false;
            $viewdefs = null;
            include($path);

            if (!empty($viewdefs)) {
                $module = key($viewdefs);
                $array = $viewdefs[$module]['base']['menu']['header'];
                $this->fixIcons($array);
                if ($this->foundPattern) {
                    sugar_file_put_contents($path, "<?php\n\n/* This file was generated by the 7_FixIconNameChanges upgrader */\n\$viewdefs['{$module}']['base']['menu']['header'] =  " . var_export($array, true) . ";\n");
                }
            }
            $viewdefs = null;
        }

    }

    /**
     * loop over view, find icons that match pattern and replace them
     * @param array $arr
     */
    protected function fixIcons(&$arr)
    {
        foreach ($arr as $key => $val) {
            if (is_array($val)) {
                $this->fixIcons($arr[$key]);
            } elseif ($key === 'icon' && preg_match($this->iconPattern, $val) && isset($this->upgradeIcons[$val])) {
                $arr[$key] = $this->upgradeIcons[$val];
                $this->foundPattern = true;
            }
        }
    }

    /**
     * Get SugarCRM instance custom modules
     *
     * @return array
     */
    protected function getCustomModules()
    {
        // Find all the classes we want to convert.
        $customModules = array();
        $customFiles = glob('modules/*/*_sugar.php', GLOB_NOSORT);

        foreach ($customFiles as $customFile) {
            $moduleName = str_replace('_sugar', '', pathinfo($customFile, PATHINFO_FILENAME));
            $customModules[] = $moduleName;
        }

        return $customModules;
    }

}
