<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN pmse_BpmnBound
 */
class pmse_BpmnBound_sugar extends Basic {
	var $new_schema = true;
	var $module_dir = 'pmse_Project/pmse_BpmnBound';
    public $module_name = 'pmse_BpmnBound';
	var $object_name = 'pmse_BpmnBound';
	var $table_name = 'pmse_bpmn_bound';
	var $importable = false;
	var $disable_custom_fields = true;
        var $id;
		var $name;
		var $date_entered;
		var $date_modified;
		var $modified_user_id;
		var $modified_by_name;
		var $created_by;
		var $created_by_name;
		var $description;
		var $deleted;
		var $created_by_link;
		var $modified_user_link;
		var $activities;
		var $assigned_user_id;
		var $assigned_user_name;
		var $assigned_user_link;
    var $bou_uid;
    var $prj_id;
    var $dia_id;
    var $element_id;
    var $bou_element;
    var $bou_element_type;
    var $bou_x;
    var $bou_y;
    var $bou_width;
    var $bou_height;
    var $bou_rel_position;
    var $bou_size_identical;
    var $bou_container;

	public function __construct(){
		parent::__construct();
	}
}
