<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */
if(empty($argv) || empty($argc) || $argc != 3) {
    die("Use UpgradeModule.php /path/to/sugar module");
}

$sapi_type = php_sapi_name();
if (substr($sapi_type, 0, 3) != 'cli') {
    die("UpgradeModule.php is CLI only.");
}

chdir($argv[1]);
define('ENTRY_POINT_TYPE', 'api');
if(!defined('sugarEntry'))define('sugarEntry', true);

require_once('include/entryPoint.php');
require_once 'modules/UpgradeWizard/SidecarUpdate/SidecarMetaDataUpgrader.php';
require_once 'include/MetaDataManager/MetaDataManager.php';

function scriptErrorHandler($errno, $errstr, $errfile, $errline, $errcontext)
{
    $GLOBALS['log']->fatal("PHP: [$errno] $errstr in $errfile at $errline"."\n".var_export(debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS), true));
}

class SidecarMetaDataUpgrader2 extends SidecarMetaDataUpgrader
{
    public function logUpgradeStatus($msg)
    {
        $GLOBALS['log']->info($msg);
    }
}

$GLOBALS['app_list_strings'] = return_app_list_strings_language($GLOBALS['current_language']);
$smdUpgrader = new SidecarMetaDataUpgrader2();
$module = $argv[2];
$smdUpgrader->setModule($module);
if(($bwcPos = array_search($module, $GLOBALS['bwcModules'])) !== false) {
    // remove it from BWC modules for now
    // if we succeed, it becomes permanent
    unset($GLOBALS['bwcModules'][$bwcPos]);
}
set_error_handler('scriptErrorHandler', E_ALL & ~E_STRICT & ~E_DEPRECATED);
$smdUpgrader->upgrade();
$fail = $smdUpgrader->getFailures();
if(!empty($fail)) {
    echo "***FAILURE***\n".var_export($fail, true)."\n";
    exit(1);
} else {
    if(count($smdUpgrader->getFilesForUpgrade()) > 0) {
        echo "\nSUCCESS!\nPlease check the result, and if you are satisfied, please delete these files:\n".join("\n", $smdUpgrader->getFilesForRemoval());
        echo "\n";
    } else {
        echo "\nNo files needed upgrade.\n";
    }
    // take module out of BWC
    if(file_exists("custom/Extension/application/Ext/Include/upgrade_bwc.php")) {
        $bwcModules = array();
        include 'custom/Extension/application/Ext/Include/upgrade_bwc.php';
        $bwcPos = array_search($module, $bwcModules);
        if($bwcPos !== false) {
            unset($bwcModules[$bwcPos]);
            // resave the file
            $data = "<?php \n/* This file was generated by Sugar Upgrade */\n";
            foreach($bwcModules as $bmodule) {
                $data .= '$bwcModules[] = \''.addslashes($bmodule)."';\n";
            }
            sugar_file_put_contents("custom/Extension/application/Ext/Include/upgrade_bwc.php", $data);
        }
    }
    // refresh caches
    SugarAutoLoader::requireWithCustom('ModuleInstall/ModuleInstaller.php');
    $moduleInstallerClass = SugarAutoLoader::customClass('ModuleInstaller');
    $mi = new $moduleInstallerClass();
    $mi->silent = true;
    $mi->rebuild_extensions();
    SugarAutoLoader::buildCache();
    // Sets up the metadata cache for the base platform only after forcefully
    // destoying the cache. Also sets up current language metadata files
    MetaDataManager::clearAPICache(true, true);
    MetaDataManager::setupMetadata(array('base'), array($GLOBALS['current_language']));
    exit(0);
}

