<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

// $Id: demoData.en_us.php 36879 2008-06-19 20:12:26Z Collin Lee $

//users demodata
//VP
global $sugar_demodata;
$sugar_demodata['users'][0] = array(
  'id' => 'seed_jim_id',	
  'last_name' => 'Brennan',
  'first_name' => 'Jim',
  'user_name' => 'jim',
  'title'	=> 'VP Sales',
  'is_admin' => false,
  'reports_to' => null,
  'reports_to_name' => null,
  'email' => 'jim@example.com'
);

//west team
$sugar_demodata['users'][] = array(
  'id' => 'seed_sarah_id',	
  'last_name' => 'Smith',
  'first_name' => 'Sarah',
  'user_name' => 'sarah',
  'title'	=> 'Sales Manager West',
  'is_admin' => false,
  'reports_to' => 'seed_jim_id',
  'reports_to_name' => 'Brennan, Jim',
  'email' => 'sarah@example.com'
);

$sugar_demodata['users'][] = array(
  'id' => 'seed_sally_id',	
  'last_name' => 'Bronsen',
  'first_name' => 'Sally',
  'user_name' => 'sally',
  'title'	=> 'Senior Account Rep',
  'is_admin' => false,
  'reports_to' => 'seed_sarah_id',
  'reports_to_name' => 'Smith, Sarah',
  'email' => 'sally@example.com'
);

$sugar_demodata['users'][] = array(
  'id' => 'seed_max_id',	
  'last_name' => 'Jensen',
  'first_name' => 'Max',
  'user_name' => 'max',
  'title'	=> 'Account Rep',
  'is_admin' => false,
  'reports_to' => 'seed_sarah_id',
  'reports_to_name' => 'Smith, Sarah',
  'email' => 'tom@example.com'
);

//east team
$sugar_demodata['users'][] = array(
  'id' => 'seed_will_id',	
  'last_name' => 'Westin',
  'first_name' => 'Will',
  'user_name' => 'will',
  'title'	=> 'Sales Manager East',
  'is_admin' => false,
  'reports_to' => 'seed_jim_id',
  'reports_to_name' => 'Brennan, Jim',
  'email' => 'will@example.com'
);

$sugar_demodata['users'][] = array(
  'id' => 'seed_chris_id',	
  'last_name' => 'Olliver',
  'first_name' => 'Chris',
  'user_name' => 'chris',
  'title'	=> 'Senior Account Rep',
  'is_admin' => false,
  'reports_to' => 'seed_will_id',
  'reports_to_name' => 'Westin, Will',
  'email' => 'chris@example.com'
);

//teams demodata
$sugar_demodata['teams'][] = array(
  'name' => 'East',	
  'description' => 'This is the team for the East',
  'team_id' => 'East',
);

$sugar_demodata['teams'][] = array(
  'name' => 'West',	
  'description' => 'This is the team for the West',
  'team_id' => 'West',
);

// tags
$sugar_demodata['tags_array'] = array(
    'follow up',
    'travel',
    'bills',
    'call back',
    'New York',
    'Seattle',
    'San Francisco',
    'Los Angeles',
    'California',
    'Washington',
    'Florida',
    'Important',
    'United States',
    'South America',
    'Asia Pacific',
    'Entertainment',
    'Local',
    'Social',
    'Global',
    'East',
    'West',
    'South',
    'North',
    'Music',
    'Arts',
    'Sciences',
    'Version',
    'Statistics',
    'University Relations',
    'Public',
    'Application',
    'Audit',
    'License',
    'Campaign',
    'Sponsers',
    'Enterprise',
    'Proprietary',
    'Professional',
    'Performance',
    'Process',
    'Standards',
    'Overview',
    'Stakeholder',
    'Bandwidth',
    'Support',
    'New Hire',
    'Europe',
    'Africa',
    'World Wide',
    'Candy Bean',
);
//contacts accounts
$sugar_demodata['last_name_array'] = array(
    'Aarons',
    'Abelson',
    'Able',
    'Abney',
    'Abram',
    'Acedo',
    'Aceto',
    'Agin',
    'Ahlquist',
    'Ahmad',
    'Ahn',
    'Aitchison',
    'Alameda',
    'Albaugh',
    'Albrecht',
    'Albright',
    'Alexandra',
    'Alfred',
    'Algarin',
    'Allen',
    'Allie',
    'Alton',
    'Ambler',
    'Ambrosino',
    'Amerine',
    'Amerman',
    'Ammon',
    'Amundsen',
    'Anaya',
    'Andersenn',
    'Andreasen',
    'Angell',
    'Angevine',
    'Angles',
    'Apo',
    'Appelbaum',
    'Archambeault',
    'Ardon',
    'Arendell',
    'Arends',
    'Arias',
    'Armstong',
    'Arvizu',
    'Asbury',
    'Aten',
    'Auclair',
    'Augustin',
    'Augustyn',
    'Auzenne',
    'Axel',
    'Axley',
    'Azevedo',
    'Backus',
    'Bagley',
    'Banda',
    'Bandy',
    'Bank',
    'Banker',
    'Banton',
    'Bare',
    'Barfoot',
    'Barish',
    'Barras',
    'Barrera',
    'Bartee',
    'Barter',
    'Basler',
    'Basta',
    'Batdorf',
    'Batista',
    'Batz',
    'Bauch',
    'Baumann',
    'Baumgart',
    'Beals',
    'Beaver',
    'Beier',
    'Beighley',
    'Bellini',
    'Benfer',
    'Beringer',
    'Bermejo',
    'Bermeo',
    'Bernat',
    'Bertram',
    'Besser',
    'Beumer',
    'Bigger',
    'Billingsley',
    'Bittle',
    'Bjornstad',
    'Blakeman',
    'Blanca',
    'Block',
    'Blohm',
    'Bloomfield',
    'Blough',
    'Boddy',
    'Boeding',
    'Boehman',
    'Bogle',
    'Bohan',
    'Boisvert',
    'Boling',
    'Boman',
    'Bondi',
    'Borge',
    'Borowski',
    'Bortz',
    'Boss',
    'Bou',
    'Bourgault',
    'Bourland',
    'Bower',
    'Boyd',
    'Boyette',
    'Bracamonte',
    'Bradbury',
    'Bramer',
    'Bramwell',
    'Brann',
    'Brantner',
    'Brar',
    'Brasher',
    'Breault',
    'Brecht',
    'Breit',
    'Brenneman',
    'Breshears',
    'Bribiesca',
    'Brickey',
    'Brimer',
    'Brinkley',
    'Brion',
    'Brister',
    'Bristol',
    'Brouse',
    'Brow',
    'Brownlow',
    'Bruck',
    'Brunetti',
    'Bruno',
    'Brunton',
    'Brzozowski',
    'Buffkin',
    'Burgan',
    'Burges',
    'Burkart',
    'Burkes',
    'Burrows',
    'Buse',
    'Bustillos',
    'Buttrey',
    'Byrom',
    'Cabot',
    'Caffee',
    'Calandra',
    'Calder',
    'Cales',
    'Canales',
    'Canova',
    'Canterbury',
    'Caperton',
    'Cardoso',
    'Cargo',
    'Caroll',
    'Carrillo',
    'Cartagena',
    'Carter',
    'Cartier',
    'Cartlidge',
    'Carwile',
    'Cassel',
    'Cassella',
    'Cast',
    'Cathey',
    'Cauthen',
    'Cavin',
    'Cazarez',
    'Cerda',
    'Cesar',
    'Chaffin',
    'Chaffins',
    'Chamorro',
    'Channell',
    'Chapel',
    'Chico',
    'Chiles',
    'Chojnacki',
    'Chow',
    'Chowdhury',
    'Christen',
    'Christoff',
    'Cimmino',
    'Cisneros',
    'Clair',
    'Clapp',
    'Clarke',
    'Clatterbuck',
    'Cleland',
    'Clingman',
    'Clore',
    'Coffee',
    'Coffelt',
    'Colletti',
    'Collins',
    'Compos',
    'Conaway',
    'Connelly',
    'Connors',
    'Constable',
    'Conyer',
    'Cooke',
    'Corbin',
    'Cordle',
    'Corpus',
    'Costillo',
    'Cotter',
    'Coulombe',
    'Councill',
    'Cozart',
    'Crabill',
    'Crepeau',
    'Croll',
    'Crosier',
    'Cryer',
    'Culbreth',
    'Cutshaw',
    'Dagen',
    'Dagley',
    'Daigle',
    'Dalton',
    'Dane',
    'Darrigo',
    'Daubert',
    'Deasy',
    'Deblasio',
    'Decato',
    'Declue',
    'Decosta',
    'Dedeaux',
    'Deem',
    'Dela',
    'Delamora',
    'Delima',
    'Demaio',
    'Derosia',
    'Devane',
    'Dibiase',
    'Dietz',
    'Dildine',
    'Dillahunt',
    'Dillion',
    'Dismukes',
    'Ditullio',
    'Doby',
    'Docherty',
    'Dockery',
    'Dodrill',
    'Donalson',
    'Doody',
    'Dora',
    'Dorn',
    'Doshier',
    'Doten',
    'Dougal',
    'Doughtie',
    'Drapeau',
    'Draves',
    'Drey',
    'Drinkard',
    'Drone',
    'Drum',
    'Drury',
    'Dry',
    'Dube',
    'Duckett',
    'Duffy',
    'Dufrene',
    'Dulmage',
    'Dundon',
    'Dunnigan',
    'Durling',
    'Dutta',
    'Eady',
    'Earley',
    'Eble',
    'Eck',
    'Edberg',
    'Eggers',
    'Ehlers',
    'Eidt',
    'Eisenbarth',
    'Ellenberger',
    'Eller',
    'Ellerman',
    'Ellingson',
    'Elmore',
    'Elridge',
    'Emig',
    'Emmer',
    'Emmett',
    'Erlandson',
    'Eslinger',
    'Esparza',
    'Esper',
    'Ester',
    'Ewen',
    'Ewert',
    'Fabiano',
    'Facio',
    'Factor',
    'Fahie',
    'Fairall',
    'Fallon',
    'Farber',
    'Fargo',
    'Farrelly',
    'Farrior',
    'Faul',
    'Fawcett',
    'Fearn',
    'Feely',
    'Ferrero',
    'Ferris',
    'File',
    'Files',
    'Filler',
    'Fillion',
    'Fils',
    'Fimbres',
    'Finkelstein',
    'Fino',
    'Fiscus',
    'Fitzwater',
    'Flamm',
    'Fleagle',
    'Fleeman',
    'Flock',
    'Florey',
    'Fogarty',
    'Follette',
    'Fong',
    'Fontana',
    'Forbes',
    'Forsyth',
    'Fragoso',
    'Freeney',
    'Fregoe',
    'Freshour',
    'Frierson',
    'Friesen',
    'Fritz',
    'Frum',
    'Fulton',
    'Funari',
    'Funaro',
    'Funk',
    'Fuquay',
    'Gadbois',
    'Gadsden',
    'Gagliardo',
    'Gailey',
    'Galang',
    'Galdamez',
    'Gale',
    'Galvan',
    'Gang',
    'Gaskell',
    'Gayer',
    'Geissler',
    'Geist',
    'Gemmell',
    'Gentner',
    'Gephart',
    'Gerling',
    'Gerner',
    'Gerrish',
    'Giblin',
    'Gibney',
    'Giddings',
    'Gieseke',
    'Gildea',
    'Gilder',
    'Gilles',
    'Gillette',
    'Gimenez',
    'Gipe',
    'Giuliani',
    'Glynn',
    'Gobert',
    'Goffney',
    'Goldberger',
    'Golder',
    'Gomer',
    'Gonsalves',
    'Gorsuch',
    'Gould',
    'Grabert',
    'Grainger',
    'Granado',
    'Granderson',
    'Grassi',
    'Greenan',
    'Greenfield',
    'Gregori',
    'Grief',
    'Griffen',
    'Grindstaff',
    'Grogan',
    'Groman',
    'Grossi',
    'Grote',
    'Grunwald',
    'Guardiola',
    'Guerrero',
    'Guilbault',
    'Guion',
    'Guizar',
    'Guttierrez',
    'Guyette',
    'Guynes',
    'Haag',
    'Haddix',
    'Hadley',
    'Hadnot',
    'Hagar',
    'Haggins',
    'Haigler',
    'Hail',
    'Haines',
    'Hakes',
    'Halcomb',
    'Hallberg',
    'Hallford',
    'Halsey',
    'Halton',
    'Halvorsen',
    'Hamada',
    'Hamby',
    'Hammaker',
    'Hammett',
    'Han',
    'Handel',
    'Haney',
    'Hannigan',
    'Hannum',
    'Hansel',
    'Haralson',
    'Harig',
    'Harker',
    'Harsch',
    'Hartig',
    'Harvell',
    'Harwood',
    'Haston',
    'Hatcher',
    'Haun',
    'Havens',
    'Hebron',
    'Hedden',
    'Heeter',
    'Heitz',
    'Henningsen',
    'Herrera',
    'Herrington',
    'Herrod',
    'Hersey',
    'Hess',
    'Hessling',
    'Hesson',
    'Heyer',
    'Hibbitts',
    'Hillary',
    'Hilton',
    'Hinson',
    'Hirata',
    'Hirst',
    'Hobart',
    'Hoch',
    'Hock',
    'Homan',
    'Hora',
    'Horowitz',
    'Hoskinson',
    'Houpt',
    'Howle',
    'Hugh',
    'Hundt',
    'Hunley',
    'Hyche',
    'Imel',
    'Imhoff',
    'Ingrassia',
    'Ireland',
    'Jackson',
    'Jacquet',
    'Jaime',
    'Janda',
    'Janusz',
    'Jeffreys',
    'Jen',
    'Jiang',
    'Jimenez',
    'Jimerson',
    'Jiron',
    'Johansen',
    'Johnstone',
    'Jorgennsen',
    'Josey',
    'Joslin',
    'Judy',
    'Jun',
    'Justis',
    'Kamen',
    'Kaminski',
    'Kang',
    'Kass',
    'Katz',
    'Kaya',
    'Keck',
    'Kellen',
    'Kellough',
    'Kelton',
    'Keplin',
    'Kerrigan',
    'Kesner',
    'Kieser',
    'Kilman',
    'Kimery',
    'Kinchen',
    'Kite',
    'Klapp',
    'Klenke',
    'Kleve',
    'Kleven',
    'Klimek',
    'Knupp',
    'Koelling',
    'Kohls',
    'Konkol',
    'Kostka',
    'Kozlowski',
    'Krauth',
    'Kroenke',
    'Kroh',
    'Krzeminski',
    'Kuehn',
    'Kuykendall',
    'Labella',
    'Labrecque',
    'Lafuente',
    'Lagarde',
    'Lague',
    'Lajeunesse',
    'Lall',
    'Lamar',
    'Lamberth',
    'Lambros',
    'Lamirande',
    'Lamoureaux',
    'Lamoureux',
    'Langone',
    'Laplant',
    'Laseter',
    'Lashua',
    'Latham',
    'Lawerence',
    'Laxton',
    'Lazaro',
    'Lazenby',
    'Leaman',
    'Leatherman',
    'Lechner',
    'Lederer',
    'Leffingwell',
    'Leiva',
    'Lema',
    'Lemasters',
    'Lemen',
    'Lessley',
    'Letellier',
    'Liao',
    'Libby',
    'Licht',
    'Lightner',
    'Limones',
    'Linderman',
    'Lingenfelter',
    'Lipsett',
    'Lipson',
    'Livengood',
    'Lizaola',
    'Loar',
    'Lockman',
    'Lomeli',
    'Longoria',
    'Loos',
    'Losoya',
    'Loughman',
    'Lovern',
    'Lubinski',
    'Lucarelli',
    'Lucey',
    'Ludlow',
    'Ludlum',
    'Lueders',
    'Lugo',
    'Lui',
    'Luick',
    'Lum',
    'Lunt',
    'Luo',
    'Lupo',
    'Lyvers',
    'Madison',
    'Madruga',
    'Magallanes',
    'Magby',
    'Mahi',
    'Mak',
    'Malcom',
    'Malin',
    'Malmberg',
    'Malta',
    'Manalo',
    'Manderscheid',
    'Manhart',
    'Manners',
    'Mapp',
    'Marcano',
    'Marcello',
    'March',
    'Marcotte',
    'Marcoux',
    'Marcus',
    'Maresca',
    'Markley',
    'Maroney',
    'Marotz',
    'Marques',
    'Maskell',
    'Massi',
    'Mathena',
    'Matheney',
    'Mathews',
    'Matsumura',
    'Matthies',
    'Matzen',
    'Maxwell',
    'Mcadory',
    'Mcardle',
    'Mcarthur',
    'Mccasland',
    'Mccawley',
    'Mcclelland',
    'Mccluney',
    'Mccoin',
    'Mccrady',
    'Mccraney',
    'Mccraw',
    'Mccurry',
    'Mcdonagh',
    'Mcelveen',
    'Mcghee',
    'Mcgillis',
    'Mcgilvery',
    'Mcguffey',
    'Mclamb',
    'Mclauchlin',
    'Mcmillan',
    'Mcmorris',
    'Mcniel',
    'Mcnitt',
    'Mcquillan',
    'Mcquillen',
    'Mcveigh',
    'Medved',
    'Meggs',
    'Mejias',
    'Mendicino',
    'Merino',
    'Michelin',
    'Mickens',
    'Mickle',
    'Midgette',
    'Miley',
    'Millikin',
    'Milling',
    'Mister',
    'Miyamoto',
    'Moffett',
    'Mohl',
    'Molder',
    'Moline',
    'Molter',
    'Monger',
    'Montesino',
    'Moots',
    'Moreno',
    'Morita',
    'Morrissey',
    'Motter',
    'Motz',
    'Moxley',
    'Moy',
    'Muhammad',
    'Munch',
    'Mungia',
    'Muszynski',
    'Myron',
    'Nakashima',
    'Needleman',
    'Neely',
    'Neil',
    'Neufeld',
    'Niemann',
    'Niemiec',
    'Niswander',
    'Noe',
    'Noell',
    'Noguera',
    'Nuff',
    'Nunemaker',
    'Oates',
    'Odegaard',
    'Ogan',
    'Ohair',
    'Ohman',
    'Okamoto',
    'Okamura',
    'Omara',
    'Openheimer',
    'Orenstein',
    'Ormond',
    'Orso',
    'Orum',
    'Ostrander',
    'Osullivan',
    'Otterson',
    'Overson',
    'Overturf',
    'Oyama',
    'Padgett',
    'Palin',
    'Panos',
    'Panter',
    'Pardee',
    'Parkerson',
    'Parkinson',
    'Parra',
    'Pasillas',
    'Paulhus',
    'Pavon',
    'Peavey',
    'Pecoraro',
    'Peeler',
    'Peffer',
    'Pelley',
    'Penhollow',
    'Penman',
    'Peoples',
    'Pero',
    'Perrault',
    'Perrotti',
    'Person',
    'Perugini',
    'Peskin',
    'Peterson',
    'Pettiway',
    'Pfarr',
    'Pfeil',
    'Phegley',
    'Phillips',
    'Picard',
    'Pickel',
    'Piermarini',
    'Pierson',
    'Piller',
    'Pina',
    'Pinnix',
    'Pinnock',
    'Pires',
    'Planck',
    'Plante',
    'Poche',
    'Polk',
    'Portnoy',
    'Posey',
    'Prange',
    'Prater',
    'Principe',
    'Printup',
    'Prosperie',
    'Pugh',
    'Pummill',
    'Puryear',
    'Quigg',
    'Radice',
    'Rahim',
    'Raines',
    'Rakestraw',
    'Ralphs',
    'Rance',
    'Rayes',
    'Redden',
    'Reiber',
    'Reinbold',
    'Remley',
    'Remo',
    'Revel',
    'Rexford',
    'Richard',
    'Richert',
    'Ridinger',
    'Rieck',
    'Rients',
    'Rimes',
    'Rio',
    'Ripley',
    'Risko',
    'Ritenour',
    'Riter',
    'Rivett',
    'Roberds',
    'Robinett',
    'Rodes',
    'Roehr',
    'Rohe',
    'Roig',
    'Roland',
    'Rolon',
    'Romeo',
    'Romig',
    'Roseborough',
    'Rosenblatt',
    'Rossbach',
    'Rosso',
    'Rota',
    'Roundy',
    'Roush',
    'Roy',
    'Rudolf',
    'Ruffino',
    'Ruley',
    'Rulison',
    'Ruple',
    'Rux',
    'Ryckman',
    'Rymer',
    'Sabatini',
    'Sadowski',
    'Saenz',
    'Saez',
    'Salters',
    'Salzer',
    'Sammet',
    'Samons',
    'Sandage',
    'Santerre',
    'Santiago',
    'Sarkis',
    'Savidge',
    'Schell',
    'Scher',
    'Schiffer',
    'Schimke',
    'Schlegel',
    'Schlueter',
    'Schneiderman',
    'Schnell',
    'Schoonmaker',
    'Schramm',
    'Schrecengost',
    'Schreiber',
    'Schroeter',
    'Schuessler',
    'Schulze',
    'Schurg',
    'Schutz',
    'Schwabe',
    'Scroggins',
    'Scull',
    'Seabaugh',
    'Seabury',
    'Sebastian',
    'Seegmiller',
    'Seely',
    'Seelye',
    'Sergent',
    'Seth',
    'Sgro',
    'Shadle',
    'Shadwick',
    'Shankle',
    'Shanley',
    'Sharp',
    'Shealey',
    'Sheard',
    'Shedrick',
    'Sheffey',
    'Shepley',
    'Shipton',
    'Shisler',
    'Shoaff',
    'Shoffner',
    'Shupe',
    'Shur',
    'Sia',
    'Sieck',
    'Siguenza',
    'Sirmons',
    'Skywalker',
    'Slater',
    'Slattery',
    'Sloan',
    'Smotherman',
    'Smullen',
    'Solie',
    'Somerville',
    'Sommer',
    'Sones',
    'Sorg',
    'Sosa',
    'Soucy',
    'Spafford',
    'Spangler',
    'Speer',
    'Sperber',
    'Spilman',
    'Spradling',
    'Spurlock',
    'Sroka',
    'Stallone',
    'Stang',
    'Stecklein',
    'Stehlik',
    'Stelzer',
    'Steppe',
    'Steuck',
    'Stidham',
    'Stiller',
    'Stoltenberg',
    'Stratman',
    'Straub',
    'Stroh',
    'Strong',
    'Stroud',
    'Stultz',
    'Sturges',
    'Sturgis',
    'Sutcliffe',
    'Suther',
    'Swann',
    'Swarey',
    'Swarthout',
    'Swayne',
    'Swindall',
    'Swindell',
    'Swing',
    'Swint',
    'Taber',
    'Tamayo',
    'Tancredi',
    'Tankersley',
    'Tanner',
    'Taube',
    'Taubman',
    'Tennison',
    'Terranova',
    'Terrio',
    'Thaler',
    'Theus',
    'Thorman',
    'Throneberry',
    'Tice',
    'Tien',
    'Timmons',
    'Tingle',
    'Tolbert',
    'Tomson',
    'Toner',
    'Tooker',
    'Toole',
    'Torbett',
    'Towsend',
    'Tranmer',
    'Trautman',
    'Treaster',
    'Trial',
    'Trisler',
    'Truluck',
    'Truman',
    'Tso',
    'Tubbs',
    'Tullos',
    'Tung',
);

$sugar_demodata['first_name_array'] = array(
    'Abby',
    'Adah',
    'Adalberto',
    'Adan',
    'Adela',
    'Adelaida',
    'Adelaide',
    'Adele',
    'Adria',
    'Adriana',
    'Adrien',
    'Adriene',
    'Afton',
    'Agatha',
    'Agnus',
    'Aida',
    'Aide',
    'Akilah',
    'Alanna',
    'Alayna',
    'Alden',
    'Aldo',
    'Aleen',
    'Alene',
    'Aleshia',
    'Alexander',
    'Alexandra',
    'Alexandria',
    'Alfreda',
    'Ali',
    'Alia',
    'Alida',
    'Alisa',
    'Alita',
    'Aliza',
    'Allegra',
    'Allyson',
    'Almeda',
    'Alona',
    'Althea',
    'Alyse',
    'Alyson',
    'Amado',
    'Amal',
    'Amelia',
    'Ammie',
    'An',
    'Ana',
    'Andera',
    'Andra',
    'Angela',
    'Angella',
    'Angla',
    'Annamarie',
    'Anne',
    'Annett',
    'Annie',
    'Antonia',
    'Antwan',
    'Anya',
    'Aracely',
    'Archie',
    'Aretha',
    'Argentina',
    'Arianne',
    'Arla',
    'Arlene',
    'Arletta',
    'Arminda',
    'Arnita',
    'Arnold',
    'Arnoldo',
    'Arthur',
    'Arturo',
    'Ashanti',
    'Ashley',
    'Ashli',
    'Assunta',
    'Astrid',
    'Audrea',
    'Aurelio',
    'Ava',
    'Avelina',
    'Barton',
    'Basilia',
    'Beaulah',
    'Belinda',
    'Bennett',
    'Benton',
    'Berenice',
    'Beryl',
    'Bethann',
    'Betsey',
    'Beula',
    'Beverlee',
    'Beverly',
    'Billie',
    'Billye',
    'Blaine',
    'Blair',
    'Bonita',
    'Bonnie',
    'Bradford',
    'Brady',
    'Brain',
    'Breana',
    'Brigette',
    'Brigitte',
    'Britney',
    'Brittanie',
    'Britteny',
    'Brittni',
    'Bronwyn',
    'Bruno',
    'Bryan',
    'Bryce',
    'Burt',
    'Byron',
    'Calista',
    'Camellia',
    'Camie',
    'Candelaria',
    'Candis',
    'Candy',
    'Cara',
    'Carey',
    'Cari',
    'Carlee',
    'Carlena',
    'Carley',
    'Carlie',
    'Carline',
    'Carlos',
    'Carlton',
    'Carly',
    'Carma',
    'Carmel',
    'Carmelia',
    'Carolann',
    'Carolina',
    'Carolyne',
    'Carolynn',
    'Caron',
    'Carroll',
    'Caryn',
    'Casandra',
    'Cassandra',
    'Cassidy',
    'Cathi',
    'Cathryn',
    'Catrina',
    'Cayla',
    'Cecila',
    'Cecille',
    'Celestina',
    'Celsa',
    'Ceola',
    'Chae',
    'Chanda',
    'Chanelle',
    'Charisse',
    'Charlsie',
    'Charlyn',
    'Charmain',
    'Chere',
    'Cheree',
    'Cherise',
    'Cherly',
    'Cherrie',
    'Chery',
    'Cheryle',
    'Chester',
    'Chia',
    'China',
    'Christal',
    'Christena',
    'Christi',
    'Christian',
    'Christoper',
    'Cinderella',
    'Cindi',
    'Cindy',
    'Clarence',
    'Claretha',
    'Clarinda',
    'Clarine',
    'Clarita',
    'Claude',
    'Claudia',
    'Clay',
    'Clelia',
    'Cleora',
    'Cleveland',
    'Cliff',
    'Clinton',
    'Clotilde',
    'Clyde',
    'Colby',
    'Coletta',
    'Conception',
    'Contessa',
    'Corazon',
    'Cordell',
    'Coretta',
    'Cori',
    'Cornelius',
    'Corrina',
    'Cortney',
    'Cory',
    'Cruz',
    'Dagmar',
    'Dallas',
    'Damian',
    'Danae',
    'Dani',
    'Danial',
    'Daniela',
    'Daniele',
    'Daniell',
    'Danilo',
    'Danna',
    'Daphne',
    'Darby',
    'Darell',
    'Darin',
    'Darnell',
    'Daron',
    'Darrell',
    'Darren',
    'Daryl',
    'Dave',
    'Debby',
    'Debera',
    'Deedra',
    'Deetta',
    'Delbert',
    'Delfina',
    'Delinda',
    'Deloise',
    'Demarcus',
    'Demetra',
    'Denna',
    'Deonna',
    'Derrick',
    'Desirae',
    'Despina',
    'Devora',
    'Dewey',
    'Dia',
    'Diamond',
    'Diane',
    'Dinorah',
    'Dixie',
    'Dodie',
    'Dominic',
    'Dominica',
    'Dominick',
    'Domitila',
    'Don',
    'Donette',
    'Doretha',
    'Dorinda',
    'Dorine',
    'Dorthea',
    'Douglass',
    'Doyle',
    'Duane',
    'Dulcie',
    'Dustin',
    'Dwain',
    'Dwana',
    'Dyan',
    'Edgar',
    'Edgardo',
    'Edison',
    'Edith',
    'Edra',
    'Effie',
    'Eilene',
    'Elda',
    'Eldora',
    'Eleanore',
    'Elena',
    'Eleni',
    'Elenore',
    'Eliana',
    'Elise',
    'Eliza',
    'Ellen',
    'Ellsworth',
    'Ellyn',
    'Elmer',
    'Elvira',
    'Elyse',
    'Elza',
    'Ema',
    'Emanuel',
    'Emerita',
    'Emmaline',
    'Emmanuel',
    'Enda',
    'Enedina',
    'Eneida',
    'Enid',
    'Enriqueta',
    'Eric',
    'Erica',
    'Erik',
    'Erika',
    'Erin',
    'Erlene',
    'Ernest',
    'Ernestina',
    'Estelle',
    'Ethyl',
    'Eugenie',
    'Eulah',
    'Eun',
    'Eusebia',
    'Eustolia',
    'Evan',
    'Evangeline',
    'Eve',
    'Evelyn',
    'Evelynn',
    'Everett',
    'Exie',
    'Fabiola',
    'Fairy',
    'Felisha',
    'Felton',
    'Fidel',
    'Filomena',
    'Flavia',
    'Florence',
    'Florencia',
    'Florene',
    'Floria',
    'Florine',
    'Floy',
    'Fran',
    'France',
    'Francie',
    'Frankie',
    'Fredericka',
    'Fredrick',
    'Gabriele',
    'Gala',
    'Gale',
    'Garret',
    'Garrett',
    'Garry',
    'Geneva',
    'Genevieve',
    'Genna',
    'Georgeanna',
    'Georgia',
    'Georgiana',
    'Gerald',
    'Gerardo',
    'Gerda',
    'German',
    'Gertha',
    'Gertrude',
    'Gia',
    'Ginette',
    'Gisela',
    'Giuseppina',
    'Gladys',
    'Glenn',
    'Glennie',
    'Glennis',
    'Gloria',
    'Gonzalo',
    'Grady',
    'Grazyna',
    'Greg',
    'Guadalupe',
    'Gustavo',
    'Guy',
    'Hal',
    'Halley',
    'Hang',
    'Hanh',
    'Hannelore',
    'Harriette',
    'Harry',
    'Hayden',
    'Heather',
    'Hector',
    'Heidy',
    'Heike',
    'Herlinda',
    'Hettie',
    'Hilaria',
    'Hillary',
    'Hipolito',
    'Hollis',
    'Homer',
    'Horace',
    'Horacio',
    'Hugh',
    'Humberto',
    'Hye',
    'Hyun',
    'Ida',
    'Ilda',
    'Imelda',
    'Indira',
    'Ingeborg',
    'Ira',
    'Iris',
    'Irma',
    'Irmgard',
    'Isa',
    'Isabell',
    'Isabella',
    'Isaura',
    'Isis',
    'Ivan',
    'Ivelisse',
    'Ivonne',
    'Ja',
    'Jackeline',
    'Jaclyn',
    'Jacquelyne',
    'Jacques',
    'Jacquline',
    'Jaime',
    'Jamal',
    'Jamar',
    'Jamila',
    'Janie',
    'Janina',
    'Janise',
    'Jansen',
    'Janyce',
    'Jarod',
    'Jaymie',
    'Jeana',
    'Jeanett',
    'Jeanetta',
    'Jeannine',
    'Jeff',
    'Jeffie',
    'Jeffry',
    'Jenette',
    'Jennefer',
    'Jennell',
    'Jennie',
    'Jerrod',
    'Jessi',
    'Jina',
    'Joana',
    'Joane',
    'Joannie',
    'Joe',
    'Joel',
    'Joellen',
    'Johana',
    'Johanne',
    'Johannes',
    'John',
    'Johnathan',
    'Johnnie',
    'Johnsie',
    'Jolene',
    'Jolie',
    'Jolyn',
    'Joseph',
    'Josette',
    'Juanita',
    'Jude',
    'Julia',
    'Juliet',
    'Juliette',
    'Julius',
    'June',
    'Justa',
    'Justine',
    'Jutta',
    'Kali',
    'Kam',
    'Kamala',
    'Kandis',
    'Kanisha',
    'Kara',
    'Karisa',
    'Karlene',
    'Karly',
    'Karolyn',
    'Karyn',
    'Kathe',
    'Katheleen',
    'Katherin',
    'Katherina',
    'Katherine',
    'Kathline',
    'Kathrin',
    'Kathyrn',
    'Katrice',
    'Kattie',
    'Kay',
    'Kaycee',
    'Kayla',
    'Kayleen',
    'Keeley',
    'Keesha',
    'Keira',
    'Keitha',
    'Kelley',
    'Kelvin',
    'Ken',
    'Kendal',
    'Kendrick',
    'Kenna',
    'Kenneth',
    'Keri',
    'Keven',
    'Kiersten',
    'Kiley',
    'Kimbra',
    'Kira',
    'Kirstin',
    'Kizzie',
    'Kortney',
    'Kristal',
    'Kristeen',
    'Kristi',
    'Kristine',
    'Krystal',
    'Krystina',
    'Krystyna',
    'Kum',
    'Kyra',
    'Lahoma',
    'Lanny',
    'Laquita',
    'Laronda',
    'Lashaunda',
    'Lashonda',
    'Lashunda',
    'Latoria',
    'Latrice',
    'Launa',
    'Lauren',
    'Laurena',
    'Lauretta',
    'Lavern',
    'Lavona',
    'Lavonda',
    'Leanora',
    'Leatha',
    'Leigha',
    'Leighann',
    'Leilani',
    'Leisha',
    'Lekisha',
    'Lenna',
    'Lennie',
    'Lenora',
    'Leo',
    'Leonel',
    'Leonida',
    'Leonie',
    'Leora',
    'Les',
    'Lesha',
    'Lester',
    'Letitia',
    'Lettie',
    'Liana',
    'Lidia',
    'Lila',
    'Lili',
    'Lily',
    'Lin',
    'Lindsay',
    'Ling',
    'Linnie',
    'Lisa',
    'Lissa',
    'Liza',
    'Lizabeth',
    'Lola',
    'Lora',
    'Loraine',
    'Loralee',
    'Loreen',
    'Lorenza',
    'Lorri',
    'Lottie',
    'Louann',
    'Louvenia',
    'Love',
    'Lovetta',
    'Lowell',
    'Loyce',
    'Lu',
    'Luba',
    'Luciana',
    'Ludie',
    'Luke',
    'Lulu',
    'Lyle',
    'Lyman',
    'Lyndsay',
    'Lynell',
    'Lynnette',
    'Ma',
    'Mabelle',
    'Machelle',
    'Mack',
    'Madalyn',
    'Madelene',
    'Madeline',
    'Madison',
    'Magaly',
    'Magda',
    'Mahalia',
    'Maia',
    'Maisie',
    'Makeda',
    'Malena',
    'Malika',
    'Malinda',
    'Malissa',
    'Mallie',
    'Man',
    'Manda',
    'Mandy',
    'Manie',
    'Manuel',
    'Many',
    'Mara',
    'Marc',
    'Marcelina',
    'Marcy',
    'Margareta',
    'Margarett',
    'Margart',
    'Marge',
    'Margit',
    'Maria',
    'Marian',
    'Mariano',
    'Marietta',
    'Marilee',
    'Marilynn',
    'Marisela',
    'Marjory',
    'Marlana',
    'Marlin',
    'Marlys',
    'Marquita',
    'Marta',
    'Marva',
    'Maryam',
    'Maryanne',
    'Marybelle',
    'Maryetta',
    'Maryjane',
    'Maryland',
    'Marylin',
    'Mathilde',
    'Matilda',
    'Matt',
    'Mattie',
    'Maura',
    'Mauricio',
    'Max',
    'Maximo',
    'Maxwell',
    'Maya',
    'Mel',
    'Melinda',
    'Melissia',
    'Mellissa',
    'Melodee',
    'Melvin',
    'Merlyn',
    'Merri',
    'Meryl',
    'Mica',
    'Micah',
    'Michaela',
    'Michelina',
    'Mikaela',
    'Mikel',
    'Milan',
    'Mildred',
    'Miles',
    'Millie',
    'Milly',
    'Mimi',
    'Minda',
    'Mindi',
    'Mindy',
    'Minta',
    'Miquel',
    'Mirian',
    'Mirta',
    'Misha',
    'Mistie',
    'Mitchell',
    'Miyoko',
    'Molly',
    'Monserrate',
    'Moses',
    'Mozell',
    'Mui',
    'Muriel',
    'Murray',
    'Myrna',
    'Myrtice',
    'Nadine',
    'Nakia',
    'Naomi',
    'Nathalie',
    'Nathan',
    'Neal',
    'Nell',
    'Nella',
    'Nelson',
    'Neomi',
    'Nereida',
    'Neta',
    'Nichelle',
    'Nichole',
    'Nickie',
    'Nima',
    'Nita',
    'Noel',
    'Noella',
    'Nolan',
    'Norman',
    'Numbers',
    'Ocie',
    'Ofelia',
    'Ollie',
    'Omega',
    'Ona',
    'Orlando',
    'Orval',
    'Otha',
    'Otis',
    'Pamela',
    'Parthenia',
    'Paula',
    'Pedro',
    'Peg',
    'Penney',
    'Peter',
    'Petronila',
    'Philip',
    'Phillis',
    'Philomena',
    'Phylicia',
    'Piedad',
    'Piper',
    'Portia',
    'Precious',
    'Queenie',
    'Quintin',
    'Rachal',
    'Rachel',
    'Raeann',
    'Rafael',
    'Ramona',
    'Ramonita',
    'Ranae',
    'Randal',
    'Randee',
    'Raylene',
    'Reatha',
    'Rebekah',
    'Reed',
    'Regan',
    'Remona',
    'Renate',
    'Renay',
    'Renda',
    'Rene',
    'Renee',
    'Reyna',
    'Rich',
    'Richelle',
    'Ricky',
    'Rigoberto',
    'Rikki',
    'Riley',
    'Robert',
    'Roberta',
    'Roberto',
    'Robin',
    'Robt',
    'Rocco',
    'Roderick',
    'Rolf',
    'Rolland',
    'Roman',
    'Ronda',
    'Ronna',
    'Ronnie',
    'Rosalina',
    'Rosalinda',
    'Rosalyn',
    'Rosanne',
    'Rosendo',
    'Rosia',
    'Roslyn',
    'Rubie',
    'Ruby',
    'Rudolf',
    'Rudy',
    'Rupert',
    'Ruthe',
    'Salina',
    'Sallie',
    'Sammy',
    'Sanda',
    'Sanford',
    'Santa',
    'Sari',
    'Sarina',
    'Saul',
    'Scottie',
    'Sebrina',
    'September',
    'Serina',
    'Setsuko',
    'Shakia',
    'Shamika',
    'Shaneka',
    'Shani',
    'Shanika',
    'Shanita',
    'Shannon',
    'Shantae',
    'Shara',
    'Shari',
    'Sharice',
    'Sharie',
    'Sharilyn',
    'Sharon',
    'Shasta',
    'Shavonda',
    'Shavonne',
    'Shawnda',
    'Shawnta',
    'Shayna',
    'Shea',
    'Sheba',
    'Sheila',
    'Shela',
    'Sheldon',
    'Shelli',
    'Shemika',
    'Shera',
    'Sherita',
    'Sherly',
    'Sherrill',
    'Sherry',
    'Sherryl',
    'Shiloh',
    'Shizuko',
    'Sho',
    'Shona',
    'Shonna',
    'Shyla',
    'Sid',
    'Signe',
    'Silas',
    'Simone',
    'Siobhan',
    'Soila',
    'Sommer',
    'Sondra',
    'Soo',
    'Soon',
    'Sophie',
    'Stacee',
    'Stanley',
    'Stanton',
    'Star',
    'Stefan',
    'Stefanie',
    'Stephine',
    'Steve',
    'Steven',
    'Suk',
    'Summer',
    'Sung',
    'Susann',
    'Susanna',
    'Suzette',
    'Synthia',
    'Tad',
    'Tai',
    'Takisha',
    'Talia',
    'Tameka',
    'Tamica',
    'Tammara',
    'Tarah',
    'Tashina',
    'Tatiana',
    'Taunya',
    'Tawana',
    'Tawna',
    'Taylor',
    'Ted',
    'Temeka',
    'Temika',
    'Tennie',
    'Terina',
    'Thea',
    'Therese',
    'Theron',
    'Thuy',
    'Tiana',
    'Tierra',
    'Tifany',
    'Tiffiny',
    'Tilda',
    'Tisa',
    'Tomi',
    'Tomiko',
    'Tona',
    'Tonda',
    'Tonette',
    'Tora',
    'Tosha',
    'Trent',
    'Treva',
    'Tricia',
    'Trinidad',
    'Trish',
    'Trudie',
    'Truman',
    'Tuan',
    'Twila',
    'Twyla',
    'Tyesha',
    'Tyrell',
    'Ute',
    'Valene',
    'Valery',
    'Van',
    'Vanda',
    'Vanesa',
    'Vanna',
    'Velda',
    'Vena',
    'Venetta',
    'Venice',
    'Vennie',
    'Verlie',
    'Vernell',
    'Veronika',
    'Vertie',
    'Veta',
    'Vickey',
    'Victor',
    'Vincenza',
    'Vincenzo',
    'Violeta',
    'Virgilio',
    'Vito',
    'Viva',
    'Wallace',
    'Walter',
    'Wan',
    'Wenona',
    'Werner',
    'Wilford',
    'Wilhemina',
    'Willene',
    'Willian',
    'Williemae',
    'Wilson',
    'Winston',
    'Winter',
    'Wonda',
    'Woodrow',
    'Wynona',
    'Xochitl',
    'Xuan',
    'Yahaira',
    'Yasuko',
    'Yee',
    'Yelena',
    'Yevette',
    'Yolanda',
    'Yolonda',
    'Youlanda',
    'Yuette',
    'Yvone',
    'Zane',
    'Zella',
);

$sugar_demodata['company_name_array'] = array(
	"24/7 Couriers",
	"Sandeon Consolidation Corp",
	"360 Vacations",
	"Powell Funding",
	"5D Investments",
	"Aim Capital Inc",
	"AB Drivers Limited",
	"Hammer Group Inc",
	"Arts & Crafts Inc",
	"A.D. Importing Company Inc",
	"A.G. Parr PLC",
	"AtoZ Co Ltd",
	"Avery Software Co",
	"Airline Maintenance Co",
	"Air Safety Inc",
	"Anytime Air Support Inc",
	"Coolview Net Ltd",
	"Rubble Group Inc",
	"B.C. Investing International",
	"Sunyvale Reporting Ltd",
	"B.H. Edwards Inc",
	"Insight Marketing Inc",
	"Bay Funding Co",
	"Nelson Inc",
	"Calm Sailing Inc",
	"Chandler Logistics Inc",
	"Cloud Cover Trust",
	"Complete Holding",
	"Constrata Trust LLC",
	"Cumberland Trails Inc",
	"DD Furniture Inc",
	"Dirt Mining Ltd",
	"Hollywood Diner Ltd",
	"Davenport Investing",
	"Draft Diversified Energy Inc",
	"First National S/B",
	"Gifted Holdings AG",
	"Green Tractor Group Limited",
	"Grow-Fast Inc",
	"Income Free Investing LP",
	"International Art Inc",
	"Ink Conglomerate Inc",
	"J.K.M. Corp (HA)",
	"JAB Funds Ltd.",
	"JBC Banking Inc",
	"JJ Resources Inc",
	"Jungle Systems Inc",
	"Kringle Bell Inc".
	"K.A. Tower & Co",
	"Kaos Trading Ltd",
	"Kings Royalty Trust",
	"King Software Inc",
	"Smith & Sons",
	"Lexington Shores Corp",
	"Max Holdings Ltd",
	"Mississippi Bank Group",
	"MMM Mortuary Corp",
	"MTM Investment Bank F S B",
	"Nimble Technologies Inc",
	"NW Bridge Construction",
	"NW Capital Corp",
	"OTC Holdings",
	"Overhead & Underfoot Ltd.",
	"P Piper & Sons",
	"Powder Suppliers",
	"Pullman Cart Company",
	"Q.R.&E. Corp",
	"Q3 ARVRO III PR",
	"Rhyme & Reason Inc",
	"Riviera Hotels",
	"RR. Talker Co",
	"RRR Advertising Inc.",
	"S Cane Sweeteners Ltd",
	"Sea Region Inc",
	"Slender Broadband Inc",
	"Smallville Resources Inc",
	"South Sea Plumbing Products",
	"Southern Realty",
	"Spend Thrift Inc",
	"Spindle Broadcast Corp.",
	"Start Over Trust",
	"Super Star Holdings Inc",
	"SuperG Tech",
	"T-Cat Media Group Inc",
	"TJ O'Rourke Inc",
	"Tortoise Corp",
	"Tracker Com LP",
	"Trait Institute Inc",
	"Tri-State Medical Corp",
	"T-Squared Techs",
	"EEE Endowments LTD",
	"Underwater Mining Inc.",
	"Union Bank",
	"Waverly Trading House",
	"White Cross Co",
	"X-Sell Holdings",
	"XY&Z Funding Inc",
);

$sugar_demodata['company_name_suffix_array'] = array(
	'Consolidated',
	'Enterprises',
	'Incorporated',
	'Limited',
	'Ventures',
	'Systems',
	'Corporation',
	'Group',
	'Products',
	'Manufacturing',
	'Holdings',
	'Consulting',
	'Solutions',
);

$sugar_demodata['street_address_array'] = array(
	 "123 Anywhere Street",
	 "345 Sugar Blvd.",
	 "1715 Scott Dr",
	 "999 Baker Way",
	 "67321 West Siam St.",
	 "48920 San Carlos Ave",
	 "777 West Filmore Ln",
	 "9 IBM Path",
	 "111 Silicon Valley Road",
	 "321 University Ave.",
 );

$sugar_demodata['city_array'] = array(
	 "San Jose",
	 "San Francisco",
	 "Sunnyvale",
	 "San Mateo",
	 "Cupertino",
	 "Los Angeles",
	 "Santa Monica",
	 "Denver",
	 "St. Petersburg",
	 "Santa Fe",
	 "Ohio",
	 "Salt Lake City",
	 "Persistance",
	 "Alabama",
	 "Kansas City",
);

//cases demodata
$sugar_demodata['case_seed_names'] = array(
	'Having trouble adding new items',
	'System not responding',
	'Need assistance with large customization',
	'Need to purchase additional licenses',
	'Warning message when using the wrong browser'
);

//bugs demodata
$sugar_demodata['bug_seed_names'] = array(
	'Error occurs while running count query',
	'Warning is displayed in file after exporting',
	'Fatal error during installation',
	'Broken image appears in home page',
	'Syntax error appears when running old reports'
);

$sugar_demodata['note_seed_names_and_Descriptions'] = array(
	array('More Account Information','This account could turn into a 3,000-user opportunity.'),
	array('Call Information','The initial sales call went well. Will follow up with contact in 3 days.'),
	array('Met at SugarCon 2010','Contact expressed interest in becoming a partner.'),
	array('Attended CRM Exceleration Event in Asia','Contact\'s event registration fee was comped.')
);

$sugar_demodata['call_seed_data_names'] = array(
	'Get more information on the proposed deal',
	'Left a message',
	'Bad time, will call back',
	'Discuss review process'
);

//titles
$sugar_demodata['titles'] = array(
	"President",
	"VP Operations",
	"VP Sales",
	"Director Operations",
	"Director Sales",
	"Mgr Operations",
	"IT Developer",
	"Senior Product Manager"
);

//tasks
$sugar_demodata['task_seed_data_names'] = array(
	'Assemble catalogs', 
	'Make travel arrangements', 
	'Send a letter', 
	'Send contract', 
	'Send fax', 
	'Send a follow-up letter', 
	'Send literature', 
	'Send proposal', 
	'Send quote', 
	'Call to schedule meeting', 
	'Setup evaluation', 
	'Get demo feedback', 
	'Arrange introduction', 
	'Escalate support request', 
	'Close out support request', 
	'Ship product', 
	'Arrange reference call', 
	'Schedule training', 
	'Send local user group information', 
	'Add to mailing list',
);

//meetings
$sugar_demodata['meeting_seed_data_names'] = array(
	'Follow-up on proposal', 
	'Initial discussion', 
	'Review needs', 
	'Discuss pricing', 
	'Demo', 
	'Introduce all players',
);
$sugar_demodata['meeting_seed_data_descriptions'] = 'Meeting to discuss project plan and hash out the details of implementation';

//emails
$sugar_demodata['email_seed_data_subjects'] = array(
	'Follow-up on proposal', 
	'Initial discussion', 
	'Review needs', 
	'Discuss pricing', 
	'Demo', 
	'Introduce all players', 
);
$sugar_demodata['email_seed_data_descriptions'] = 'Important Meeting to discuss ' .
    'project plan and hash out the details of implementation';
$sugar_demodata['email_seed_data_description_html'] = '<p><strong>Important</strong> ' .
    'Meeting to discuss project plan and hash out the details of implementation.</p>';
$sugar_demodata['email_seed_data_types'] = array(
    'inbound',
    'draft',
    'out',
);

//leads
$sugar_demodata['primary_address_state'] = 'CA';
$sugar_demodata['billing_address_state']['east'] = 'NY';
$sugar_demodata['billing_address_state']['west'] = 'CA';
$sugar_demodata['primary_address_country'] = 'USA';

//manufacturers
$sugar_demodata['manufacturer_seed_data_names'] = array(
	'TekWare Inc.', 
	'Acme Suppliers'
);

//Shippers
$sugar_demodata['shipper_seed_data_names'] = array(
	'FedEx', 
	'USPS Ground'
);

//productcategories
$sugar_demodata['category_ext_name'] = ' Widgets';
$sugar_demodata['product_ext_name'] = ' Gadget';
$sugar_demodata['productcategory_seed_data_names'] = array(
	'Desktops', 
	'Laptops', 
	'Stationary Device', 
	'Modular Device'
);

//producttype
$sugar_demodata['producttype_seed_data_names']= array(
	'Devices', 
	'Hardware', 
	'Support Contract'
);

//taxrate
$sugar_demodata['taxrate_seed_data'][] = array(
	'name' => '8.25 - Cupertino, CA',
	'value' => '8.25',
);

$sugar_demodata['currency_seed_data'][] = array(
	'name' => 'Euro',
	'conversion_rate' => 0.9,
	'iso4217' => 'EUR',
	'symbol' => '€',
);

//producttemplate
$sugar_demodata['producttemplate_seed_data'][] = array(
	'name' => 'TK 1000 Desktop',
	'tax_class' => 'Taxable',
	'cost_price' => 500.00,
	'cost_usdollar' => 500.00,
	'list_price' => 800.00,
	'list_usdollar' => 800.00,
	'discount_price' => 800.00,
	'discount_usdollar' => 800.00,
	'pricing_formula' => 'IsList',
	'mft_part_num' => 'XYZ7890122222',
	'pricing_factor' => '1',
	'status' => 'Available',
	'weight' => 20.0,
	'date_available' => '2009-10-15',
	'qty_in_stock' => '72',
); 

$sugar_demodata['producttemplate_seed_data'][] = array(
	'name' => 'TK 1000 Desktop',
	'tax_class' => 'Taxable',
	'cost_price' => 600.00,
	'cost_usdollar' => 600.00,
	'list_price' => 900.00,
	'list_usdollar' => 900.00,
	'discount_price' => 900.00,
	'discount_usdollar' => 900.00,
	'pricing_formula' => 'IsList',
	'mft_part_num' => 'XYZ7890123456',
	'pricing_factor' => '1',
	'status' => 'Available',
	'weight' => 20.0,
	'date_available' => '2009-10-15',
	'qty_in_stock' => '65',
); 

$sugar_demodata['producttemplate_seed_data'][] = array(
	'name' => 'TK m30 Desktop',
	'tax_class' => 'Taxable',
	'cost_price' => 1300.00,
	'cost_usdollar' => 1300.00,
	'list_price' => 1700.00,
	'list_usdollar' => 1700.00,
	'discount_price' => 1625.00,
	'discount_usdollar' => 1625.00,
	'pricing_formula' => 'ProfitMargin',
	'mft_part_num' => 'ABCD123456890',
	'pricing_factor' => '20',
	'status' => 'Available',
	'weight' => 5.0,
	'date_available' => '2009-10-15',
	'qty_in_stock' => '12',
); 

$sugar_demodata['producttemplate_seed_data'][] = array(
	'name' => 'Reflective Mirror Widget',
	'tax_class' => 'Taxable',
	'cost_price' => 200.00,
	'cost_usdollar' => 200.00,
	'list_price' => 325.00,
	'list_usdollar' => 325.00,
	'discount_price' => 266.50,
	'discount_usdollar' => 266.50,
	'pricing_formula' => 'PercentageDiscount',
	'mft_part_num' => '2.0',
	'pricing_factor' => '20',
	'status' => 'Available',
	'weight' => 20.0,
	'date_available' => '2009-10-15',
	'qty_in_stock' => '65',
); 


// KBDocuments
$sugar_demodata['kbcategories_array'] = array(
    'Documentation' => array(
        'Calendar',
        'Calls',
        'Email',
        'Database'
    ),
    'Tutorials' => array(),
    'Video' => array(),
    'Help' => array()
);

$sugar_demodata['kbdocuments_statuses'] = array(
    'draft',
    'in-review',
    'approved',
    'published',
);

$sugar_demodata['kbdocuments_languages'] = array(
    array(
        'en' => 'English',
        'primary' => true
    ),
    array(
        'de' => 'Deutsch',
        'primary' => false
    ),
);

$sugar_demodata['kbdocuments_seed_data'][] = array(
    'name' => 'Connecting to the Internet',
    'body' => '<p>To connect your device to the Internet, use any application that accesses the Internet. You can connect using either Wi-Fi or Bluetooth.</p>',
    'tag' => '^WiFi^,^Bluetooth^,^Networking^',
    'localizations' => array(
        array(
            'language' => 'de',
            'name' => 'Verbinden mit dem Internet',
            'body' => '<p>Um das Gerät mit dem Internet verbinden, verwenden Sie alle Anwendungen, die auf das Internet zugreift. Sie können eine Verbindung sowohl mit der Wi-Fi oder Bluetooth.</p>'
        )
    )
);
$sugar_demodata['kbdocuments_seed_data'][] = array(
    'name' => 'Charging the battery',
    'body' => '<p>To charge the battery, try the following:</p>
    <ul><li>Connect device to a power outlet using the included cable and the USB power adapter.</li>
    <li>Connect to a high-power USB 2.0 port using the included cable.</li></ul>',
    'tag' => '^Basic Usage^,^Hardware^',
    'revisions' => array(
        array(
            'name' => 'Charging the battery - revision 2'
        ),
        array(
            'name' => 'Charging the battery - revision 3'
        )
    )
);
$sugar_demodata['kbdocuments_seed_data'][] = array(
    'name' => 'How to print',
    'active_date' => '2015-01-01',
    'exp_date' => '2015-12-31',
    'useful' => 10,
    'notuseful' => 5,
    'body' => '<p>In order to print, you first need to send your file to your computer. Access and print the file from your computer.</p>',
    'tag' => '^Basic Usage^,^Tools^',
);

$sugar_demodata['kbdocuments_seed_data'][] = array(
    'name' => 'How to change the language',
    'active_date' => '2015-01-01',
    'exp_date' => '2015-12-31',
    'useful' => 8,
    'notuseful' => 12,
    'body' => '<p>If your device is not set to your preferred language, please make sure you have completed the setup. In the Settings screen, select Languages. Select the language you prefer.</p>',
    'tag' => '^Basic Usage^,^OS and Interface^',
);

$sugar_demodata['kbdocuments_seed_data'][] = array(
    'name' => 'Resetting the device',
    'active_date' => '2014-01-01',
    'exp_date' => '2014-12-31',
    'body' => '<p>When things are not working as expected, try resetting the device. Hold the Start button until the dialog box displays.  Select the Reset option.</p>',
    'tag' => '^Basic Usage^,^Hardware^',
);
$sugar_demodata['contract_seed_data'][] = array(
	'name' => 'IT Tech Support for UK Datacenter',
	'reference_code' => 'EMP-9802',
	'total_contract_value' => '500600.01',
	'start_date' => '2010-05-15',
	'end_date' => '2020-05-15',
	'company_signed_date' => '2010-03-15',
	'customer_signed_date' => '2010-03-16',
	'description' => 'This is a sub-contract for a very large project.',
); 

$sugar_demodata['contract_seed_data'][] = array(
	'name' => 'Ion Engines for Auto Plant',
	'reference_code' => 'EMP-7277',
	'total_contract_value' => '333444.34',
	'start_date' => '2010-05-15',
	'end_date' => '2020-05-15',
	'company_signed_date' => '2010-03-15',
	'customer_signed_date' => '2010-03-16',
	'description' => 'In competition with Sienar Fleet Systems for this one.',
);

//BEGIN Quotes demo data
$sugar_demodata['quotes_seed_data']['quotes'][0] = array(
	'name' => 'Computers for [account name]',
	'quote_stage' => 'Draft',
	'date_quote_expected_closed' => '2012-04-30',
    'description' => '',
    'purcahse_order_num' => '6011842',
    'payment_terms' => 'Net 30',

    'bundle_data' => array(
		0 => array (
		    'bundle_name' => 'Computers',
		    'bundle_stage' => 'Draft',
		    'comment' => 'TK Desktop Computers',
		    'products' => array (
				1 => array('name'=>'TK 1000 Desktop', 'quantity'=>'1'),
				2 => array('name'=>'TK m30 Desktop', 'quantity'=>'2'),
			),
		),
	),
);


$sugar_demodata['quotes_seed_data']['quotes'][1] = array(
	'name' => 'Mirrors for [account name]',
	'quote_stage' => 'Negotiation',
	'date_quote_expected_closed' => '2012-04-30',
    'description' => '',
 	'purcahse_order_num' => '3940021',
    'payment_terms' => 'Net 15',
         

    'bundle_data' => array(
		0 => array (
		    'bundle_name' => 'Mirrors',
		    'bundle_stage' => 'Draft',
		    'comment' => 'Reflective Mirrors',
		    'products' => array (
				1 => array('name'=>'Reflective Mirror Widget', 'quantity'=>'2'),
			),
		),
	),
);
//END Quotes demo data

//BEGIN Opportunities demo data
$sugar_demodata['opportunities_seed_data']['opportunities'][1] = array(

    'bundle_data' => array(
		0 => array (
		    'bundle_name' => 'Mirrors',
		    'bundle_stage' => 'Draft',
		    'comment' => 'Reflective Mirrors',
		    'products' => array (
				1 => array('name'=>'Reflective Mirror Widget', 'quantity'=>'2'),
			),
		),


        0 => array (
      		    'bundle_name' => 'Mirrors',
      		    'bundle_stage' => 'Draft',
      		    'comment' => 'Reflective Mirrors',
      		    'products' => array (
      				1 => array('name'=>'Reflective Mirror Widget', 'quantity'=>'2'),
      			),
      	),

	),
);
//END Opportunities demo data

//BEGIN Data Privacy demo data
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Send copy of privacy policy',
    'status' => 'Open',
    'type' => 'Request for Data Privacy Policy',
    'priority' => 'Low',
    'source' => 'Email',
    'requested_by' => 'By the person themselves',
    'description' => 'Contact would like to review our privacy policy and wants a copy',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Send copy of revised privacy policy',
    'status' => 'Closed',
    'type' => 'Request for Data Privacy Policy',
    'priority' => 'Low',
    'source' => 'Web Form',
    'requested_by' => 'By the person themselves',
    'description' => 'We have sent an older version of the privacy policy and they would like to see the updated policy',
    'resolution' => 'An updated policy was sent via email.',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Send personal information being captured in CRM',
    'status' => 'Open',
    'type' => 'Send Personal Information being processed',
    'priority' => 'Low',
    'source' => 'Phone',
    'requested_by' => 'By the person themselves',
    'description' => 'Wants to know the details of all information captured in our CRM system',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Inquiry about personal information captured',
    'status' => 'Closed',
    'type' => 'Send Personal Information being processed',
    'priority' => 'Low',
    'source' => 'Email',
    'requested_by' => 'By the person themselves',
    'description' => 'Wants details of the personal information captured by us',
    'resolution' => 'Copied information personal information viewer and emailed to the person',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Request to check and send personal information',
    'status' => 'Rejected',
    'type' => 'Send Personal Information being processed',
    'priority' => 'Low',
    'source' => 'Email',
    'requested_by' => 'By the person themselves',
    'description' => 'Wanted to check if any personal information was being recorded',
    'resolution' => 'Subject is not eligible to receive a copy of the personal data as per legal. They can request again once legal challenges are resolved.',
    'work_log' => 'Checking with legal on applicability',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Change the phone number in record',
    'status' => 'Open',
    'type' => 'Rectify Information',
    'priority' => 'Medium',
    'source' => 'Email',
    'requested_by' => 'By the person themselves',
    'description' => 'New work phone in 555-787-9087',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Change title and company name',
    'status' => 'Closed',
    'type' => 'Rectify Information',
    'priority' => 'Medium',
    'source' => 'Email',
    'requested_by' => 'By the person themselves',
    'description' => 'Person has changed company. We need to correct this information. New company is Acme Software. New Title is Director Business Development. No email provided.',
    'resolution' => 'Information rectified and confirmed in audit log',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Would like to erase and forget',
    'status' => 'Open',
    'type' => 'Request to Erase Information',
    'priority' => 'High',
    'source' => 'Email',
    'requested_by' => 'By the person themselves',
    'description' => 'Subject wants to completely forget about them',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Request to remove social data',
    'status' => 'Closed',
    'type' => 'Request to Erase Information',
    'priority' => 'High',
    'source' => 'Email',
    'requested_by' => 'By the person themselves',
    'description' => 'This person wants us to remove their social links',
    'resolution' => 'Information erased and informed subject via email',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Request to erase record completely',
    'status' => 'Rejected',
    'type' => 'Request to Erase Information',
    'priority' => 'High',
    'source' => 'Email',
    'requested_by' => 'By the person themselves',
    'description' => 'Person has requested to be erased completely',
    'resolution' => 'Request was reject as there is a outstanding balance. Email was sent to the person.',
    'work_log' => "There is an outstanding balance with this company. Record cannot be erased until all arrears are paid.\n\nChecking if there is any outstanding work items",
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Request for an electronic copy of data',
    'status' => 'Open',
    'type' => 'Export Information',
    'priority' => 'Medium',
    'source' => 'Email',
    'requested_by' => 'By the person themselves',
    'description' => 'Person wants access to all personal data stored in our systems',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Request for an electronic copy of personal data',
    'status' => 'Closed',
    'type' => 'Export Information',
    'priority' => 'Medium',
    'source' => 'Email',
    'requested_by' => 'By the person themselves',
    'description' => 'Would like to receive an electronic copy of personal data',
    'resolution' => 'Exported data from List view and emailed a subset to person',
    'work_log' => 'Confirmed that subject is under purview of GDPR and has data subject rights',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Request copy of all data',
    'status' => 'Rejected',
    'type' => 'Export Information',
    'priority' => 'Medium',
    'source' => 'Email',
    'requested_by' => 'By the person themselves',
    'description' => 'Would like to receive an electronic copy of personal data',
    'resolution' => 'Request rejected. Emal has been sent with the decision.',
    'work_log' => 'Subject is not EU resident and is not under purview. Recommend to reject request',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Would like to request the processing be stopped',
    'status' => 'Open',
    'type' => 'Restrict Processing',
    'priority' => 'High',
    'source' => 'Email',
    'requested_by' => 'By the person themselves',
    'description' => 'Wants to restrict the processing of personal data',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Wants to stop processing of data',
    'status' => 'Closed',
    'type' => 'Restrict Processing',
    'priority' => 'High',
    'source' => 'Email',
    'requested_by' => 'By the person themselves',
    'description' => 'Wants to restrict the processing of personal data',
    'resolution' => 'Record has been marked for restriction',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Requesting to stop processing of personal data',
    'status' => 'Rejected',
    'type' => 'Restrict Processing',
    'priority' => 'High',
    'source' => 'Email',
    'requested_by' => 'By the person themselves',
    'description' => 'Wants to restrict the processing of personal data',
    'resolution' => 'Request rejected. Emal has been sent with the decision.',
    'work_log' => 'Subject is not EU resident and is not under purview. Recommend to reject request',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Objects to processing of personal data',
    'status' => 'Open',
    'type' => 'Object to Processing',
    'priority' => 'High',
    'source' => 'Email',
    'requested_by' => 'By the person themselves',
    'description' => 'Wants to restrict the processing of personal data',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Request related to objection of processing',
    'status' => 'Closed',
    'type' => 'Object to Processing',
    'priority' => 'High',
    'source' => 'Email',
    'requested_by' => 'By the person themselves',
    'description' => 'Wants to restrict the processing of personal data',
    'resolution' => 'Record has been marked for restriction',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Requesting to stop processing of personal data',
    'status' => 'Rejected',
    'type' => 'Object to Processing',
    'priority' => 'High',
    'source' => 'Email',
    'requested_by' => 'By the person themselves',
    'description' => 'Wants to restrict the processing of personal data',
    'resolution' => 'Request rejected. Emal has been sent with the decision.',
    'work_log' => 'Subject is not EU resident and is not under purview. Recommend to reject request',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Received consent to process',
    'status' => 'Closed',
    'type' => 'Consent to Process',
    'priority' => 'Medium',
    'source' => 'web form',
    'requested_by' => 'By the person themselves',
    'description' => 'Consent was received',
    'resolution' => 'Consent recorded in record',
    'business_purpose' => '^Business Communications^,^Marketing Communications by company^',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Withdraws consent for marketing',
    'status' => 'Open',
    'type' => 'Withdraw Consent',
    'priority' => 'Medium',
    'source' => 'Email',
    'requested_by' => 'By the person themselves',
    'description' => 'Would like to withdraw consent',
    'business_purpose' => '^Marketing Communications by company^,^Marketing Communications by partners^',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Withdraws consent for partner marketing',
    'status' => 'Closed',
    'type' => 'Withdraw Consent',
    'priority' => 'Medium',
    'source' => 'phone',
    'requested_by' => 'By the person themselves',
    'description' => 'Would like to withdraw consent',
    'resolution' => 'Accepted. Email sent. Contact record updated.',
    'business_purpose' => '^Marketing Communications by partners^',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Withdraws consent for partner marketing',
    'status' => 'Rejected',
    'type' => 'Withdraw Consent',
    'priority' => 'Medium',
    'source' => 'Email',
    'requested_by' => 'By the person themselves',
    'description' => 'Would like to withdraw consent',
    'resolution' => 'Request rejected. Emal has been sent with the decision.',
    'work_log' => 'Consent cannot be removed for business communications as per policy',
    'business_purpose' => '^Business Communications^ ',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Wanted to find out if our company is compliant with regulations',
    'status' => 'Closed',
    'type' => 'Other',
    'priority' => 'Low',
    'source' => 'Email',
    'requested_by' => 'By the person themselves',
    'description' => 'email sent with link to the web site on privacy policy',
    'resolution' => 'EMail sent',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Request for personal information captured in CRM',
    'status' => 'Open',
    'type' => 'Send Personal Information being processed',
    'priority' => 'Low',
    'source' => 'Phone',
    'requested_by' => 'By the person themselves',
    'description' => 'Wants to know the details of all information captured in our CRM system',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Send personal information ',
    'status' => 'Open',
    'type' => 'Send Personal Information being processed',
    'priority' => 'Low',
    'source' => 'Phone',
    'requested_by' => 'By the person themselves',
    'description' => 'Wants to know the details of all information captured in our CRM system',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Send personal information being captured in CRM',
    'status' => 'Open',
    'type' => 'Send Personal Information being processed',
    'priority' => 'Low',
    'source' => 'Phone',
    'requested_by' => 'By the person themselves',
    'description' => 'Wants to know the details of all information captured in our CRM system',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Request for a copy of data',
    'status' => 'Open',
    'type' => 'Export Information',
    'priority' => 'Medium',
    'source' => 'Email',
    'requested_by' => 'By the person themselves',
    'description' => 'Subject is requesting a copy of all personal information captured on them',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Request for an electronic copy of personal data',
    'status' => 'Open',
    'type' => 'Export Information',
    'priority' => 'Medium',
    'source' => 'Email',
    'requested_by' => 'By the person themselves',
    'description' => 'Requesting an electronic copy of personal data stored',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Request for a copy of personal information ',
    'status' => 'Open',
    'type' => 'Export Information',
    'priority' => 'Medium',
    'source' => 'Email',
    'requested_by' => 'By the person themselves',
    'description' => 'Request for a copy of personal information',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Request for an electronic copy of data',
    'status' => 'Open',
    'type' => 'Export Information',
    'priority' => 'Medium',
    'source' => 'Email',
    'requested_by' => 'By the person themselves',
    'description' => 'Request for an electronic copy of data',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Want us to erase personal data',
    'status' => 'Open',
    'type' => 'Request to Erase Information',
    'priority' => 'High',
    'source' => 'Email',
    'requested_by' => 'By the person themselves',
    'description' => 'Want us to erase personal data because they are getting a lot of junk mail',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'No business, Erase data',
    'status' => 'Open',
    'type' => 'Request to Erase Information',
    'priority' => 'High',
    'source' => 'Email',
    'requested_by' => 'By the person themselves',
    'description' => 'Request to erase data as they have not done any business with our company in the past 4 years',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Erase personal data per lack of consent',
    'status' => 'Open',
    'type' => 'Request to Erase Information',
    'priority' => 'High',
    'source' => 'Email',
    'requested_by' => 'By the person themselves',
    'description' => 'Subject is upset that consent was not provided, and hence data should be erased and no further communication should be allowed',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Forget about my record',
    'status' => 'Open',
    'type' => 'Request to Erase Information',
    'priority' => 'High',
    'source' => 'Email',
    'requested_by' => 'By the person themselves',
    'description' => 'Would like us to forget about their record completely from all systems',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Received consent to process',
    'status' => 'Closed',
    'type' => 'Consent to Process',
    'priority' => 'Medium',
    'source' => 'web form',
    'requested_by' => 'By the person themselves',
    'description' => 'Consent was received',
    'resolution' => 'Consent recorded in record',
    'business_purpose' => '^Business Communications^,^Marketing Communications by company^,^Marketing Communications by partners^',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Received consent to process',
    'status' => 'Closed',
    'type' => 'Consent to Process',
    'priority' => 'Medium',
    'source' => 'web form',
    'requested_by' => 'By the person themselves',
    'description' => 'Consent was received',
    'resolution' => 'Consent recorded in record',
    'business_purpose' => '^Business Communications^,^Marketing Communications by company^,^Marketing Communications by partners^',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Received consent to process',
    'status' => 'Closed',
    'type' => 'Consent to Process',
    'priority' => 'Medium',
    'source' => 'web form',
    'requested_by' => 'By the person themselves',
    'description' => 'Consent was received',
    'resolution' => 'Consent recorded in record',
    'business_purpose' => '^Business Communications^,^Marketing Communications by company^,^Marketing Communications by partners^',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Received consent to process',
    'status' => 'Closed',
    'type' => 'Consent to Process',
    'priority' => 'Medium',
    'source' => 'web form',
    'requested_by' => 'By the person themselves',
    'description' => 'Consent was received',
    'resolution' => 'Consent recorded in record',
    'business_purpose' => '^Business Communications^,^Marketing Communications by company^,^Marketing Communications by partners^',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Received consent to process',
    'status' => 'Closed',
    'type' => 'Consent to Process',
    'priority' => 'Medium',
    'source' => 'web form',
    'requested_by' => 'By the person themselves',
    'description' => 'Consent was received',
    'resolution' => 'Consent recorded in record',
    'business_purpose' => '^Business Communications^,^Marketing Communications by company^,^Marketing Communications by partners^',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Received consent to process',
    'status' => 'Closed',
    'type' => 'Consent to Process',
    'priority' => 'Medium',
    'source' => 'web form',
    'requested_by' => 'By the person themselves',
    'description' => 'Consent was received',
    'resolution' => 'Consent recorded in record',
    'business_purpose' => '^Business Communications^,^Marketing Communications by company^,^Marketing Communications by partners^',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Received consent to process',
    'status' => 'Closed',
    'type' => 'Consent to Process',
    'priority' => 'Medium',
    'source' => 'web form',
    'requested_by' => 'By the person themselves',
    'description' => 'Consent was received',
    'resolution' => 'Consent recorded in record',
    'business_purpose' => '^Business Communications^,^Marketing Communications by company^,^Marketing Communications by partners^',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Want us to erase personal data',
    'status' => 'Open',
    'type' => 'Request to Erase Information',
    'priority' => 'High',
    'source' => 'Email',
    'requested_by' => 'By the person themselves',
    'description' => 'Want us to erase personal data because they are getting a lot of spam',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'No business, Erase data',
    'status' => 'Open',
    'type' => 'Request to Erase Information',
    'priority' => 'High',
    'source' => 'Email',
    'requested_by' => 'By the person themselves',
    'description' => 'Requet to erase data as they have not done any business with our company in the past 2 years',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Erase personal data per lack of consent',
    'status' => 'Open',
    'type' => 'Request to Erase Information',
    'priority' => 'High',
    'source' => 'Email',
    'requested_by' => 'By the person themselves',
    'description' => 'Subject is upset that consent was not provided, and hence data should be erased and no further communication should be allowed',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'ERase data about minors',
    'status' => 'Open',
    'type' => 'Request to Erase Information',
    'priority' => 'High',
    'source' => 'Email',
    'requested_by' => 'By the parent of person',
    'description' => 'The parent of this person called and would like to completely erase their minors data',
    'resolution' => 'Confirmed that subject is a minor and is subject to erasure. Informed Data Privacy Manager',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Requests to correct information',
    'status' => 'Open',
    'type' => 'Rectify Information',
    'priority' => 'Medium',
    'source' => 'Email',
    'requested_by' => 'By the person themselves',
    'description' => 'New work phone in 510-737-9876',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Change email address',
    'status' => 'Open',
    'type' => 'Rectify Information',
    'priority' => 'Medium',
    'source' => 'Email',
    'requested_by' => 'By the person themselves',
    'description' => 'New email address is jwc@acme.com',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Change company and title',
    'status' => 'Open',
    'type' => 'Rectify Information',
    'priority' => 'Medium',
    'source' => 'Email',
    'requested_by' => 'By the person themselves',
    'description' => 'Company name is Whitehouse marketing, Title is VP Marketing',
);
$sugar_demodata['dataprivacy_seed_data'][] = array(
    'name' => 'Would like to request the processing be stopped',
    'status' => 'Open',
    'type' => 'Restrict Processing',
    'priority' => 'High',
    'source' => 'Email',
    'requested_by' => 'By the person themselves',
    'description' => 'Wants to restrict the processing of personal data',
);
//END Data Privacy demo data
