<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN pmse_BpmRelatedDependency
 */
class pmse_BpmRelatedDependency_sugar extends Basic {
	var $new_schema = true;
	var $module_dir = 'pmse_Project/pmse_BpmRelatedDependency';
    public $module_name = 'pmse_BpmRelatedDependency';
	var $object_name = 'pmse_BpmRelatedDependency';
	var $table_name = 'pmse_bpm_related_dependency';
	var $importable = false;
    var $disable_custom_fields = true;
        var $id;
		var $name;
		var $date_entered;
		var $date_modified;
		var $modified_user_id;
		var $modified_by_name;
		var $created_by;
		var $created_by_name;
		var $description;
		var $deleted;
		var $created_by_link;
		var $modified_user_link;
		var $activities;
		var $assigned_user_id;
		var $assigned_user_name;
		var $assigned_user_link;
    var $evn_id;
    var $evn_uid;
    var $evn_marker;
    var $evn_is_interrupting;
    var $evn_attached_to;
    var $evn_cancel_activity;
    var $evn_activity_ref;
    var $evn_wait_for_completion;
    var $evn_error_name;
    var $evn_error_code;
    var $evn_escalation_name;
    var $evn_escalation_code;
    var $evn_condition;
    var $evn_message;
    var $evn_operation_name;
    var $evn_operation_implementation;
    var $evn_time_date;
    var $evn_time_cycle;
    var $evn_time_duration;
    var $evn_behavior;
    var $evn_status;
    var $evn_type;
    var $evn_module;
    var $evn_criteria;
    var $evn_params;
    var $evn_script;
    var $prj_id;
    var $pro_id;
    var $pro_module;
    var $pro_status;
    var $pro_locked_variables;
    var $pro_terminate_variables;
    var $rel_element_id;
    var $rel_element_type;
    var $rel_process_module;
    var $rel_element_module;
    var $rel_element_relationship;


	public function __construct(){
		parent::__construct();
	}
}
